export const EVENTS = {
  USER_WELCOME: "USER_WELCOME",

  ORDER_CREATED: "ORDER_CREATED",

  ORDER_SHIPPED: "ORDER_SHIPPED",

  ORDER_OUT_FOR_DELIVERY:
    "ORDER_OUT_FOR_DELIVERY",

  ORDER_DELIVERED: "ORDER_DELIVERED",

  ORDER_FAILED: "ORDER_FAILED",

  FEEDBACK_REQUEST: "FEEDBACK_REQUEST",

  CART_RECOVERY: "CART_RECOVERY",

  PROMO_CAMPAIGN: "PROMO_CAMPAIGN",

  LOW_STOCK: "LOW_STOCK",

  OUT_OF_STOCK: "OUT_OF_STOCK",

  DAILY_REPORT: "DAILY_REPORT",

  WEEKLY_REPORT: "WEEKLY_REPORT",

  MONTHLY_REPORT: "MONTHLY_REPORT",

  SYSTEM_ERROR: "SYSTEM_ERROR",
};