// src/config/eventTemplateMap.js

import { EVENT_TYPES } from "./eventTypes.js";
import { TEMPLATE_IDS } from "./templateIds.js";

export const EVENT_TEMPLATE_MAP = {
  [EVENT_TYPES.USER_REGISTERED]:
    TEMPLATE_IDS.USER_WELCOME,

  [EVENT_TYPES.ORDER_CREATED]:
    TEMPLATE_IDS.ORDER_CREATED,

  [EVENT_TYPES.ORDER_PACKED]:
    TEMPLATE_IDS.ORDER_PACKED,

  [EVENT_TYPES.ORDER_SHIPPED]:
    TEMPLATE_IDS.ORDER_SHIPPED,

  [EVENT_TYPES.ORDER_OUT_FOR_DELIVERY]:
    TEMPLATE_IDS.ORDER_OUT_FOR_DELIVERY,

  [EVENT_TYPES.ORDER_DELIVERED]:
    TEMPLATE_IDS.ORDER_DELIVERED,

  [EVENT_TYPES.ORDER_CANCELLED]:
    TEMPLATE_IDS.ORDER_CANCELLED,

  [EVENT_TYPES.FEEDBACK_REQUEST]:
    TEMPLATE_IDS.FEEDBACK_REQUEST,

  [EVENT_TYPES.CART_ABANDONED]:
    TEMPLATE_IDS.CART_RECOVERY,

  [EVENT_TYPES.PROMO_CAMPAIGN]:
    TEMPLATE_IDS.PROMO_CAMPAIGN,

  [EVENT_TYPES.NEW_DROP_ALERT]:
    TEMPLATE_IDS.NEW_DROP_ALERT,

  [EVENT_TYPES.RETURN_REQUESTED]:
    TEMPLATE_IDS.RETURN_REQUESTED,

  [EVENT_TYPES.RETURN_PICKUP_SCHEDULED]:
    TEMPLATE_IDS.RETURN_PICKUP_SCHEDULED,

  [EVENT_TYPES.RETURN_RECEIVED]:
    TEMPLATE_IDS.RETURN_RECEIVED,

  [EVENT_TYPES.REFUND_INITIATED]:
    TEMPLATE_IDS.REFUND_INITIATED,

  [EVENT_TYPES.REFUND_PROCESSED]:
    TEMPLATE_IDS.REFUND_PROCESSED,

  [EVENT_TYPES.LOW_STOCK]:
    TEMPLATE_IDS.LOW_STOCK,

  [EVENT_TYPES.OUT_OF_STOCK]:
    TEMPLATE_IDS.OUT_OF_STOCK,

  [EVENT_TYPES.SYSTEM_ERROR]:
    TEMPLATE_IDS.SYSTEM_ERROR,

  [EVENT_TYPES.DAILY_REPORT]:
    TEMPLATE_IDS.DAILY_REPORT,

  [EVENT_TYPES.WEEKLY_REPORT]:
    TEMPLATE_IDS.WEEKLY_REPORT,

  [EVENT_TYPES.MONTHLY_REPORT]:
    TEMPLATE_IDS.MONTHLY_REPORT,
};