// src/config/templateIds.js

export const TEMPLATE_IDS = {
  // Customer

  USER_WELCOME: "DRIPZOID_USER_WELCOME",

  ORDER_CREATED: "DRIPZOID_ORDER_CREATED",

  ORDER_PACKED: "DRIPZOID_ORDER_PACKED",

  ORDER_SHIPPED: "DRIPZOID_ORDER_SHIPPED",

  ORDER_OUT_FOR_DELIVERY:
    "DRIPZOID_ORDER_OUT_FOR_DELIVERY",

  ORDER_DELIVERED: "DRIPZOID_ORDER_DELIVERED",

  ORDER_CANCELLED: "DRIPZOID_ORDER_CANCELLED",

  FEEDBACK_REQUEST: "DRIPZOID_FEEDBACK_REQUEST",

  CART_RECOVERY: "DRIPZOID_CART_RECOVERY",

  PROMO_CAMPAIGN: "DRIPZOID_PROMO_CAMPAIGN",

  NEW_DROP_ALERT: "DRIPZOID_NEW_DROP_ALERT",

  // Returns & Refunds

  RETURN_REQUESTED:
    "DRIPZOID_RETURN_REQUESTED",

  RETURN_PICKUP_SCHEDULED:
    "DRIPZOID_RETURN_PICKUP_SCHEDULED",

  RETURN_RECEIVED:
    "DRIPZOID_RETURN_RECEIVED",

  REFUND_INITIATED:
    "DRIPZOID_REFUND_INITIATED",

  REFUND_PROCESSED:
    "DRIPZOID_REFUND_PROCESSED",

  // Admin

  LOW_STOCK: "DRIPZOID_LOW_STOCK",

  OUT_OF_STOCK: "DRIPZOID_OUT_OF_STOCK",

  SYSTEM_ERROR: "DRIPZOID_SYSTEM_ERROR",

  DAILY_REPORT: "DRIPZOID_DAILY_REPORT",

  WEEKLY_REPORT: "DRIPZOID_WEEKLY_REPORT",

  MONTHLY_REPORT: "DRIPZOID_MONTHLY_REPORT",
};